### ISSUE TITLE
Dragon conversion completely non-functional

### ISSUE THREAD

**Issue by Ultimushadow** [ArshiaDPG/Diamond-In-The-Rough-Fabric#2]
Threw this into a big pack to test out, the dragon fireball conversion wasn't working so I went to test it on its own and yeah, it doesn't work in general. I'm on 1.20.1 Fabric 0.14.22 with version 1.1.0 of this mod.
First thing I thought to look for is the tags, while the ore replaceables was loaded, dragon_made_ores does not exist in the mod folder. Unfortunately, that didn't fix my issue, and the mod still doesn't convert any obsidian into the ore.
I've attached a log but it's basically empty. I test mods with Mod Menu, Jade, EMI, StackDeobfuscator, Better Log4j Config, YACL and Dashloader. Afaik none of these should be interacting with your mod's ability to alter the world. 
[latest.log](https://github.com/ArshiaDPG/Diamond-In-The-Rough-Fabric/files/12447674/latest.log)

At some point while testing I actually got a crash but I have no idea what caused it. The game crashed as soon as one of the fireballs hit the obsidian. I have Carpet, Neruina and Collective loaded here but again, I don't suspect these are the reason at all.
[crash-2023-08-27_04.05.54-server.txt](https://github.com/ArshiaDPG/Diamond-In-The-Rough-Fabric/files/12447686/crash-2023-08-27_04.05.54-server.txt)
Unfortunately I no longer have the log that preceded the crash.

**Comment by ArshiaDPG** [comment]
Yes I've encountered this error as well, we've hopefully fixed it in the 1.1.1 patch.
